// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package id.ice.tiktok_api_android


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class TikTokLoginStatus(val raw: Int) {
  SUCCESS(0),
  CANCELLED(1),
  ERROR(2);

  companion object {
    fun ofRaw(raw: Int): TikTokLoginStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TikTokLoginResult (
  val status: TikTokLoginStatus,
  val authCode: String? = null,
  val state: String? = null,
  val codeVerifier: String? = null,
  val errorCode: String? = null,
  val errorMessage: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): TikTokLoginResult {
      val status = TikTokLoginStatus.ofRaw(list[0] as Int)!!
      val authCode = list[1] as String?
      val state = list[2] as String?
      val codeVerifier = list[3] as String?
      val errorCode = list[4] as String?
      val errorMessage = list[5] as String?
      return TikTokLoginResult(status, authCode, state, codeVerifier, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      status.raw,
      authCode,
      state,
      codeVerifier,
      errorCode,
      errorMessage,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object TiktokSDKApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TikTokLoginResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TikTokLoginResult -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TiktokSDKApi {
  fun setup(clientKey: String, callback: (Result<Unit>) -> Unit)
  fun login(scopes: List<String>, redirectUri: String, browserAuthEnabled: Boolean?, callback: (Result<TikTokLoginResult>) -> Unit)

  companion object {
    /** The codec used by TiktokSDKApi. */
    val codec: MessageCodec<Any?> by lazy {
      TiktokSDKApiCodec
    }
    /** Sets up an instance of `TiktokSDKApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: TiktokSDKApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tiktok_api_android.TiktokSDKApi.setup", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientKeyArg = args[0] as String
            api.setup(clientKeyArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tiktok_api_android.TiktokSDKApi.login", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val scopesArg = args[0] as List<String>
            val redirectUriArg = args[1] as String
            val browserAuthEnabledArg = args[2] as Boolean?
            api.login(scopesArg, redirectUriArg, browserAuthEnabledArg) { result: Result<TikTokLoginResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
